# Generated by Django 2.2.7 on 2019-11-13 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('desc', models.TextField(max_length=20000)),
                ('cre_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
